version: '3.5'

services:

  postgres:
    image: postgres:latest
    restart: on-failure
    hostname: postgres
    environment:
      - POSTGRES_DB=itaudb
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./dbconfig/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - local

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    networks:
      - local

  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: api-fake
    ports:
      - 8081:8080
    volumes:
      - ./extensions:/var/wiremock/extensions
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]

  json_server:
    image: clue/json-server
    restart: on-failure
    ports:
      - 8090:80
    volumes:
      - ./fake-api/db.json:/data/db.json
    networks:
      - local

networks:
  local:
    driver: bridge