version: '3.5'

services:

  postgres:
    image: postgres:latest
    restart: on-failure
    hostname: postgres
    environment:
      - POSTGRES_DB=itaudb
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./dbconfig/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - local

  json_server:
    image: clue/json-server
    restart: on-failure
    ports:
      - 8090:80
    volumes:
      - ./fake-api/db.json:/data/db.json
    networks:
      - local

networks:
  local:
    driver: bridge