version: '3.5'

services:

  postgres:
    image: postgres:latest
    restart: on-failure
    hostname: postgres
    environment:
      - POSTGRES_DB=itaudb
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/dbconfig/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - local

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - ./docker-volumes/redis_data:/data
    networks:
      - local


  json_server:
    image: clue/json-server
    restart: on-failure
    ports:
      - 8090:80
    volumes:
      - ./docker-volumes/fake-api/db.json:/data/db.json
    networks:
      - local
#  wiremock:
#    image: "wiremock/wiremock:latest"
#    container_name: api-fake
#    ports:
#      - 8081:8080
#    volumes:
#      - ./docker-volumes/extensions:/var/wiremock/extensions
#      - ./docker-volumes/__files:/home/wiremock/__files
#      - ./docker-volumes/mappings:/home/wiremock/mappings
#    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]

networks:
  local:
    driver: bridge